# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: karen ho
email: hokarenj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web developer and data analysis professional in Toronto, Ontario, Canada.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://karenjho.com" # the base hostname & protocol for your site
twitter_username: karenjho
github_username:  karenjho

# Build settings
markdown: kramdown
